name: flutter_learning
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.13.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  flutter_bloc: ^9.1.1
  http: ^1.6.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/

  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Italic.ttf
          style: italic
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GoogleSans-SemiBoldItalic.ttf
          weight: 600
          style: italic

    - family: Scaver
      fonts:
        - asset: assets/fonts/Scaver-Regular-BF69add6b13806e.ttf
        - asset: assets/fonts/Scaver-Italic-BF69add6b14d9c5.ttf
          style: italic
        - asset: assets/fonts/Scaver-Bold-BF69add6b0c3a74.ttf
          weight: 700
        - asset: assets/fonts/Scaver-BoldItalic-BF69add6b08087c.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Scaver-Medium-BF69add6b1210f5.ttf
          weight: 500
        - asset: assets/fonts/Scaver-MediumItalic-BF69add6b0af747.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Scaver-Light-BF69add6b109a2f.ttf
          weight: 300
        - asset: assets/fonts/Scaver-LightItalic-BF69add6b142723.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Scaver-ExtraLight-BF69add6b0d9719.ttf
          weight: 200
        - asset: assets/fonts/Scaver-ExtraLightItalic-BF69add6b0ce852.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Scaver-ExtraBold-BF69add6b0f1846.ttf
          weight: 800
        - asset: assets/fonts/Scaver-ExtraBoldItalic-BF69add6b0e56b3.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Scaver-Black-BF69add6b08da24.ttf
          weight: 900
        - asset: assets/fonts/Scaver-BlackItalic-BF69add6b0b9a9f.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Scaver-SemiBold-BF69add6b12d146.ttf
          weight: 600
        - asset: assets/fonts/Scaver-SemiBoldItalic-BF69add6b0988b4.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Scaver-Thin-BF69add6b114d5a.ttf
          weight: 100
        - asset: assets/fonts/Scaver-ThinItalic-BF69add6b0a3008.ttf
          weight: 100
          style: italic

